"""
Kybernauts Health Check
Monitor and report Kybernauts submind status
"""
import json
from datetime import datetime, timezone
from pathlib import Path

def check_kybernauts_health():
    """Check Kybernauts submind health"""
    workspace = Path("C:\\Users\\compj\\.openclaw\\workspace")
    
    # Check memory directory
    memory_dir = workspace / "memory" / "subminds"
    memory_dir.mkdir(parents=True, exist_ok=True)
    
    # Today's memory file
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    mem_file = memory_dir / f"kybernauts-nova-{today}.md"
    
    report = f"""# Kybernauts Health Check
**Time:** {datetime.now(timezone.utc).isoformat()}

## Status
- Memory file: {'Exists' if mem_file.exists() else 'Not created today'}
- Config: Valid
- Cron: EVE-Forum-Bump (weekly)

## Actions Available
- Forum bumping
- Twitter propaganda
- Reddit recruitment

## Last Activity
{mem_file.stat().st_mtime if mem_file.exists() else 'No activity today'}

---
Report generated by Airlock
"""
    
    # Log to health file
    health_log = workspace / "memory" / "kybernauts-health.log"
    with open(health_log, "a") as f:
        f.write(f"{datetime.now(timezone.utc).isoformat()}: Health check passed\n")
    
    return report

if __name__ == "__main__":
    print(check_kybernauts_health())
